### ISSUE TITLE
.so文件

### ISSUE THREAD

**Issue by dtczhl** [panyingyun/vtkandroiddemo#2]
我在ubuntu 18.04没有编译成功，你能不能把编译后的.so文件和头文件发给我？ 
我的邮箱zhanghuanle1342@gmail.com
谢谢了

**Comment by panyingyun** [comment]
VTK编译后的静态库（非动态库）见
https://github.com/panyingyun/vtkandroiddemo/blob/master/vtkandroid/vtk-android.tar.gz
JavaVTK的so在对应的工程下
https://github.com/panyingyun/vtkandroiddemo/blob/master/JavaVTK2/app/src/main/jniLibs/armeabi-v7a/libJavaVTK.so

**Comment by dtczhl** [comment]
你好，

我用了你的.a静态库，但总是有下面的error
[image: 1.png]

我用android studio
在CMakeLists.txt里我添加你的所有库
比如

add_library(libvtkCommonColor STATIC IMPORTED)
set_target_properties(libvtkCommonColor PROPERTIES IMPORTED_LOCATION
${CMAKE_SOURCE_DIR}/vtk/lib/libvtkCommonColor-8.2.a)

target_link_libraries( # Specifies the target library.
        native-lib
        # libpcl_2d libpcl_common libpcl_features libpcl_filters
libpcl_io libpcl_io_ply libpcl_kdtree libpcl_keypoints libpcl_ml
libpcl_octree libpcl_recognition libpcl_registration
libpcl_sample_consensus libpcl_search libpcl_segmentation
libpcl_stereo libpcl_surface libpcl_tracking
        # libboost_date_time libboost_filesystem libboost_iostreams
libboost_program_options libboost_regex libboost_signals
libboost_system libboost_thread
        # libflann_cpp_s libflann_s
        libvtkCommonColor libvtkCommonComputationalGeometry
libvtkCommonCore libvtkCommonDataModel libvtkCommonExecutionModel
libvtkCommonMath libvtkCommonMisc libvtkCommonSystem
libvtkCommonTransforms libvtkDICOMParser libvtkFiltersCore
libvtkFiltersExtraction libvtkFiltersGeneral libvtkFiltersGeometry
libvtkFiltersModeling libvtkFiltersSources libvtkFiltersStatistics
libvtkIOCore libvtkIOGeometry libvtkIOImage libvtkIOInfovis
libvtkIOLegacy libvtkIOPLY libvtkIOXML libvtkIOXMLParser
libvtkImagingCore libvtkImagingFourier libvtkImagingMath
libvtkInfovisCore libvtkInteractionStyle libvtkParallelCore
libvtkRenderingCore libvtkRenderingFreeType libvtkRenderingOpenGL2
libvtkRenderingVolume libvtkRenderingVolumeOpenGL2
libvtkTestingRendering libvtkdoubleconversion libvtkexpat
libvtkfreetype libvtkglew libvtkjpeg libvtklibxml2 libvtklz4
libvtklzma libvtkmetaio libvtkpng libvtksys libvtktiff libvtkzlib
        # Links the target library to the log library
        # included in the NDK.
        ${log-lib})

添加头文件

include_directories(${CMAKE_SOURCE_DIR}/vtk/include)

native-lib.cpp里include头文件，随便写了行代码就有出现上面的错误

vtkSmartPointer<vtkSphereSource> sphereSource =
vtkSmartPointer<vtkSphereSource>::New();


Java MianActivity.java

static {
    System.loadLibrary("native-lib");
}


除此之外还需要配置什么吗？

Thanks,
Huanle Zhang

**Comment by panyingyun** [comment]
按照我的blog编译看看，步骤比较详细：https://www.michaelapp.com/posts/2019/VTK-Android%E7%A7%BB%E6%A4%8D%E5%92%8C%E7%A4%BA%E4%BE%8B/

**Comment by dtczhl** [comment]
我重新跑了个ubuntu 16.04 docker，根据你的blog，编译成功了
但是在android studio运行时还是一样的链接错误

我看到vtk-android下面有个cmake目录，这个目录需要吗？该怎么用呢？

**Comment by dtczhl** [comment]
你能否创建一个空的android studio java项目， 使用编译后的.a库(不是javavtk2.so)？
写个最小的程序

我对比下是不是我的配置问题。

谢谢

**Comment by panyingyun** [comment]
javavtk2.so 是用这些.a文件链接起来的，链接脚本在
https://github.com/panyingyun/vtkandroiddemo/blob/master/JavaVTK2/app/src/main/cpp/CMakeLists.txt
参考里面的配置即可
https://github.com/panyingyun/vtkandroiddemo/tree/master/JavaVTK2/app/src/main/cpp
这个即编译 javavtk.so的工程文件目录，看下相关文件。

**Comment by dtczhl** [comment]
@panyingyun 非常感谢！

**Comment by panyingyun** [comment]
不用客气

**Comment by zhouyan33** [comment]
我按照你的方法，但是没有成功，可以给一下编译后的.so文件吗
