### ISSUE TITLE
vtk三维重建

### ISSUE THREAD

**Issue by flamx** [panyingyun/vtkandroiddemo#3]
您好，我是一名大四学生，我的毕业设计需要制作一个dicom医学图像的可视化系统，我想做一个android端的app，现在已经实现了选择本地图片并显示。我先是通过python完成了其他功能已经用vtk实现三维重建，但是在android上实现图像三维重建的时候卡住了很久。
网上找到的资料太少了，终于在github上找到一些模块，我想的先是实现这些模块，再移植到自己项目中，最后再实现本地选取文件显示等功能，但是在第一步就遇到许多问题。我知道您用的是linux系统，但我在虚拟机中文件共享出了问题，就想在windows中实现，教程上前面一些步骤就都完成不了，就直接运行的demo1，javaVTK1,VolumeRender,VTK3DEarth这几个项目，但我不太清楚他们的区别，结果都运行不了。
我还看到另一个Android-vtk-skeleton，里面好像是缺少库文件，我把您的vtk-android.tar的压缩包解压到那个文件夹，然后把VTK DIR设置成里面的...\vtkandroid\vtk-android\lib\cmake\vtk-8.2，但是也还是会报错。
希望您能抽空指教一下。

**Comment by SpringLuocl** [comment]
您好，我最近打算在android实现一个简单mpr功能，在这之前有在linux上跑过相关的例子，但是把代码功能移植到android上就显示不了图像。
在rk3399设备上可以显示原图，但是通过颜色映射处理后就会报错，在普通的手机上测试，没有报错，但是显示的图片会异常（看不出来显示的是什么）
请问您有没有其他android平台的对图片读取进行处理的例子可以借鉴下？谢谢!
